# Generated by Django 3.2.9 on 2021-11-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('guid', models.CharField(max_length=70)),
                ('link', models.URLField(max_length=300)),
                ('pubDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'symbol',
                'verbose_name_plural': 'symbols',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=512)),
                ('active', models.BooleanField(default=True)),
                ('symbols', models.ManyToManyField(blank=True, to='feeds.Symbol')),
            ],
            options={
                'verbose_name': 'feed',
                'verbose_name_plural': 'feeds',
            },
        ),
    ]
