# Generated by Django 3.2.9 on 2021-11-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feednews_s'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feednews',
            options={'verbose_name': 'feed news', 'verbose_name_plural': 'feed news'},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='url',
        ),
        migrations.AddField(
            model_name='symbol',
            name='url',
            field=models.URLField(default='test', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='symbols',
            field=models.ManyToManyField(to='feeds.Symbol'),
        ),
        migrations.AlterField(
            model_name='feednews',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
